### ISSUE TITLE
unable to build the project

### ISSUE THREAD

**Issue by acche** [JeffBNimble/LoLBookOfChampions-swift2-sqlite#2]
How to run up this project, need to run Carthage and cocoapods ? And lots of error to build it.

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/Supporting Files/LoLBookOfChampions-Bridging-Header.h:13:9: error: 'AFNetworking/AFNetworking.h' file not found
# import <AFNetworking/AFNetworking.h>

```
    ^
```

<unknown>:0: error: failed to import bridging header '/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/Supporting Files/LoLBookOfChampions-Bridging-Header.h'

**Comment by JeffBNimble** [comment]
Yes, you need to first use Carthage AND CocoaPods to resolve the dependencies. Unfortunately both are required because all of the dependencies do not yet support Carthage.

Please refer to the README for installation instructions.

https://github.com/JeffBNimble/LoLBookOfChampions-swift2-sqlite#installation

I'm marking this closed assuming that the instructions will resolve your problem. If not, please re-open with specific details. I hope this helps.

**Comment by acche** [comment]
Follow the instructions to run both Carthage And Cocoapods to pre-setup the project. But it is still some error occurred while build the project.

---

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:15:64: 'Sink' is not a member type of 'Event<(Uri, ContentOperation), NoError>' (aka 'Event<(NSURL, ContentOperation), NoError>')

---

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:16:56: 'Sink' is not a member type of 'Event<(Uri, ContentOperation), NoError>' (aka 'Event<(NSURL, ContentOperation), NoError>')

---

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:21:9: Use of unresolved identifier 'sendNext'

---

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Signals.swift:31:35: Cannot invoke initializer for type 'AppContentObserver' with an argument list of type '(sink: Observer<(Uri, ContentOperation), NoError>)'

---

/Users/my/Downloads/LoLBookOfChampions-swift2-sqlite-master/LoLBookOfChampions/util/Actions.swift:72:21: Use of unresolved identifier 'sendCompleted'

---

How can I resolved those error?
